insert into url_map (url_from, url_to, date) values ('/jobs/africa','/seasonal-jobs-working-holidays/africa', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/africa' where section_uri = (select section_uri from article_map where section_uri = '/jobs/africa');
insert into url_map (url_from, url_to, date) values ('/jobs/andorra','/seasonal-jobs-working-holidays/andorra', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/andorra' where section_uri = (select section_uri from article_map where section_uri = '/jobs/andorra');
insert into url_map (url_from, url_to, date) values ('/jobs/argentina','/seasonal-jobs-working-holidays/argentina', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/argentina' where section_uri = (select section_uri from article_map where section_uri = '/jobs/argentina');
insert into url_map (url_from, url_to, date) values ('/jobs/asia','/seasonal-jobs-working-holidays/asia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/asia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/asia');
insert into url_map (url_from, url_to, date) values ('/jobs/australasia-pacific','/seasonal-jobs-working-holidays/australasia-pacific', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australasia-pacific' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australasia-pacific');
insert into url_map (url_from, url_to, date) values ('/jobs/australia','/seasonal-jobs-working-holidays/australia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/adelaide','/seasonal-jobs-working-holidays/australia/adelaide', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/adelaide' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/adelaide');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/brisbane','/seasonal-jobs-working-holidays/australia/brisbane', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/brisbane' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/brisbane');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/cairns','/seasonal-jobs-working-holidays/australia/cairns', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/cairns' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/cairns');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/canberra','/seasonal-jobs-working-holidays/australia/canberra', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/canberra' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/canberra');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/melbourne','/seasonal-jobs-working-holidays/australia/melbourne', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/melbourne' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/melbourne');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/northern-territory','/seasonal-jobs-working-holidays/australia/northern-territory', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/northern-territory' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/northern-territory');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/perth','/seasonal-jobs-working-holidays/australia/perth', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/perth' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/perth');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/queensland','/seasonal-jobs-working-holidays/australia/queensland', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/queensland' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/queensland');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/sydney','/seasonal-jobs-working-holidays/australia/sydney', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/sydney' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/sydney');
insert into url_map (url_from, url_to, date) values ('/jobs/australia/tasmania','/seasonal-jobs-working-holidays/australia/tasmania', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/australia/tasmania' where section_uri = (select section_uri from article_map where section_uri = '/jobs/australia/tasmania');
insert into url_map (url_from, url_to, date) values ('/jobs/austria','/seasonal-jobs-working-holidays/austria', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/austria' where section_uri = (select section_uri from article_map where section_uri = '/jobs/austria');
insert into url_map (url_from, url_to, date) values ('/jobs/bahamas','/seasonal-jobs-working-holidays/bahamas', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/bahamas' where section_uri = (select section_uri from article_map where section_uri = '/jobs/bahamas');
insert into url_map (url_from, url_to, date) values ('/jobs/belgium','/seasonal-jobs-working-holidays/belgium', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/belgium' where section_uri = (select section_uri from article_map where section_uri = '/jobs/belgium');
insert into url_map (url_from, url_to, date) values ('/jobs/belize','/seasonal-jobs-working-holidays/belize', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/belize' where section_uri = (select section_uri from article_map where section_uri = '/jobs/belize');
insert into url_map (url_from, url_to, date) values ('/jobs/bhutan','/seasonal-jobs-working-holidays/bhutan', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/bhutan' where section_uri = (select section_uri from article_map where section_uri = '/jobs/bhutan');
insert into url_map (url_from, url_to, date) values ('/jobs/bolivia','/seasonal-jobs-working-holidays/bolivia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/bolivia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/bolivia');
insert into url_map (url_from, url_to, date) values ('/jobs/brazil','/seasonal-jobs-working-holidays/brazil', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/brazil' where section_uri = (select section_uri from article_map where section_uri = '/jobs/brazil');
insert into url_map (url_from, url_to, date) values ('/jobs/cambodia','/seasonal-jobs-working-holidays/cambodia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/cambodia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/cambodia');
insert into url_map (url_from, url_to, date) values ('/jobs/canada','/seasonal-jobs-working-holidays/canada', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/canada' where section_uri = (select section_uri from article_map where section_uri = '/jobs/canada');
insert into url_map (url_from, url_to, date) values ('/jobs/caribbean','/seasonal-jobs-working-holidays/caribbean', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/caribbean' where section_uri = (select section_uri from article_map where section_uri = '/jobs/caribbean');
insert into url_map (url_from, url_to, date) values ('/jobs/central-america','/seasonal-jobs-working-holidays/central-america', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/central-america' where section_uri = (select section_uri from article_map where section_uri = '/jobs/central-america');
insert into url_map (url_from, url_to, date) values ('/jobs/chile','/seasonal-jobs-working-holidays/chile', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/chile' where section_uri = (select section_uri from article_map where section_uri = '/jobs/chile');
insert into url_map (url_from, url_to, date) values ('/jobs/china','/seasonal-jobs-working-holidays/china', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/china' where section_uri = (select section_uri from article_map where section_uri = '/jobs/china');
insert into url_map (url_from, url_to, date) values ('/jobs/colombia','/seasonal-jobs-working-holidays/colombia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/colombia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/colombia');
insert into url_map (url_from, url_to, date) values ('/jobs/costa-rica','/seasonal-jobs-working-holidays/costa-rica', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/costa-rica' where section_uri = (select section_uri from article_map where section_uri = '/jobs/costa-rica');
insert into url_map (url_from, url_to, date) values ('/jobs/croatia','/seasonal-jobs-working-holidays/croatia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/croatia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/croatia');
insert into url_map (url_from, url_to, date) values ('/jobs/cuba','/seasonal-jobs-working-holidays/cuba', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/cuba' where section_uri = (select section_uri from article_map where section_uri = '/jobs/cuba');
insert into url_map (url_from, url_to, date) values ('/jobs/cyprus','/seasonal-jobs-working-holidays/cyprus', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/cyprus' where section_uri = (select section_uri from article_map where section_uri = '/jobs/cyprus');
insert into url_map (url_from, url_to, date) values ('/jobs/cyprus/ayia-napa','/seasonal-jobs-working-holidays/cyprus/ayia-napa', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/cyprus/ayia-napa' where section_uri = (select section_uri from article_map where section_uri = '/jobs/cyprus/ayia-napa');
insert into url_map (url_from, url_to, date) values ('/jobs/czech-republic','/seasonal-jobs-working-holidays/czech-republic', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/czech-republic' where section_uri = (select section_uri from article_map where section_uri = '/jobs/czech-republic');
insert into url_map (url_from, url_to, date) values ('/jobs/denmark','/seasonal-jobs-working-holidays/denmark', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/denmark' where section_uri = (select section_uri from article_map where section_uri = '/jobs/denmark');
insert into url_map (url_from, url_to, date) values ('/jobs/dubai','/seasonal-jobs-working-holidays/dubai', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/dubai' where section_uri = (select section_uri from article_map where section_uri = '/jobs/dubai');
insert into url_map (url_from, url_to, date) values ('/jobs/ecuador','/seasonal-jobs-working-holidays/ecuador', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/ecuador' where section_uri = (select section_uri from article_map where section_uri = '/jobs/ecuador');
insert into url_map (url_from, url_to, date) values ('/jobs/egypt','/seasonal-jobs-working-holidays/egypt', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/egypt' where section_uri = (select section_uri from article_map where section_uri = '/jobs/egypt');
insert into url_map (url_from, url_to, date) values ('/jobs/estonia','/seasonal-jobs-working-holidays/estonia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/estonia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/estonia');
insert into url_map (url_from, url_to, date) values ('/jobs/europe','/seasonal-jobs-working-holidays/europe', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/europe' where section_uri = (select section_uri from article_map where section_uri = '/jobs/europe');
insert into url_map (url_from, url_to, date) values ('/jobs/fiji','/seasonal-jobs-working-holidays/fiji', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/fiji' where section_uri = (select section_uri from article_map where section_uri = '/jobs/fiji');
insert into url_map (url_from, url_to, date) values ('/jobs/finland','/seasonal-jobs-working-holidays/finland', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/finland' where section_uri = (select section_uri from article_map where section_uri = '/jobs/finland');
insert into url_map (url_from, url_to, date) values ('/jobs/france','/seasonal-jobs-working-holidays/france', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/france' where section_uri = (select section_uri from article_map where section_uri = '/jobs/france');
insert into url_map (url_from, url_to, date) values ('/jobs/galapagos-islands','/seasonal-jobs-working-holidays/galapagos-islands', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/galapagos-islands' where section_uri = (select section_uri from article_map where section_uri = '/jobs/galapagos-islands');
insert into url_map (url_from, url_to, date) values ('/jobs/germany','/seasonal-jobs-working-holidays/germany', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/germany' where section_uri = (select section_uri from article_map where section_uri = '/jobs/germany');
insert into url_map (url_from, url_to, date) values ('/jobs/greece','/seasonal-jobs-working-holidays/greece', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece');
insert into url_map (url_from, url_to, date) values ('/jobs/greece/crete','/seasonal-jobs-working-holidays/greece/crete', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece/crete' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece/crete');
insert into url_map (url_from, url_to, date) values ('/jobs/greece/kavos','/seasonal-jobs-working-holidays/greece/kavos', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece/kavos' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece/kavos');
insert into url_map (url_from, url_to, date) values ('/jobs/greece/malia','/seasonal-jobs-working-holidays/greece/malia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece/malia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece/malia');
insert into url_map (url_from, url_to, date) values ('/jobs/greece/mykonos','/seasonal-jobs-working-holidays/greece/mykonos', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece/mykonos' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece/mykonos');
insert into url_map (url_from, url_to, date) values ('/jobs/greece/rhodes','/seasonal-jobs-working-holidays/greece/rhodes', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece/rhodes' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece/rhodes');
insert into url_map (url_from, url_to, date) values ('/jobs/greece/santorini','/seasonal-jobs-working-holidays/greece/santorini', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece/santorini' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece/santorini');
insert into url_map (url_from, url_to, date) values ('/jobs/greece/zante','/seasonal-jobs-working-holidays/greece/zante', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/greece/zante' where section_uri = (select section_uri from article_map where section_uri = '/jobs/greece/zante');
insert into url_map (url_from, url_to, date) values ('/jobs/honduras','/seasonal-jobs-working-holidays/honduras', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/honduras' where section_uri = (select section_uri from article_map where section_uri = '/jobs/honduras');
insert into url_map (url_from, url_to, date) values ('/jobs/hong-kong','/seasonal-jobs-working-holidays/hong-kong', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/hong-kong' where section_uri = (select section_uri from article_map where section_uri = '/jobs/hong-kong');
insert into url_map (url_from, url_to, date) values ('/jobs/hungary','/seasonal-jobs-working-holidays/hungary', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/hungary' where section_uri = (select section_uri from article_map where section_uri = '/jobs/hungary');
insert into url_map (url_from, url_to, date) values ('/jobs/iceland','/seasonal-jobs-working-holidays/iceland', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/iceland' where section_uri = (select section_uri from article_map where section_uri = '/jobs/iceland');
insert into url_map (url_from, url_to, date) values ('/jobs/india','/seasonal-jobs-working-holidays/india', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/india' where section_uri = (select section_uri from article_map where section_uri = '/jobs/india');
insert into url_map (url_from, url_to, date) values ('/jobs/indonesia','/seasonal-jobs-working-holidays/indonesia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/indonesia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/indonesia');
insert into url_map (url_from, url_to, date) values ('/jobs/indonesia/bali','/seasonal-jobs-working-holidays/indonesia/bali', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/indonesia/bali' where section_uri = (select section_uri from article_map where section_uri = '/jobs/indonesia/bali');
insert into url_map (url_from, url_to, date) values ('/jobs/indonesia/jakarta','/seasonal-jobs-working-holidays/indonesia/jakarta', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/indonesia/jakarta' where section_uri = (select section_uri from article_map where section_uri = '/jobs/indonesia/jakarta');
insert into url_map (url_from, url_to, date) values ('/jobs/ireland','/seasonal-jobs-working-holidays/ireland', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/ireland' where section_uri = (select section_uri from article_map where section_uri = '/jobs/ireland');
insert into url_map (url_from, url_to, date) values ('/jobs/israel','/seasonal-jobs-working-holidays/israel', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/israel' where section_uri = (select section_uri from article_map where section_uri = '/jobs/israel');
insert into url_map (url_from, url_to, date) values ('/jobs/italy','/seasonal-jobs-working-holidays/italy', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/italy' where section_uri = (select section_uri from article_map where section_uri = '/jobs/italy');
insert into url_map (url_from, url_to, date) values ('/jobs/japan','/seasonal-jobs-working-holidays/japan', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/japan' where section_uri = (select section_uri from article_map where section_uri = '/jobs/japan');
insert into url_map (url_from, url_to, date) values ('/jobs/jordan','/seasonal-jobs-working-holidays/jordan', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/jordan' where section_uri = (select section_uri from article_map where section_uri = '/jobs/jordan');
insert into url_map (url_from, url_to, date) values ('/jobs/korea','/seasonal-jobs-working-holidays/korea', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/korea' where section_uri = (select section_uri from article_map where section_uri = '/jobs/korea');
insert into url_map (url_from, url_to, date) values ('/jobs/laos','/seasonal-jobs-working-holidays/laos', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/laos' where section_uri = (select section_uri from article_map where section_uri = '/jobs/laos');
insert into url_map (url_from, url_to, date) values ('/jobs/malaysia','/seasonal-jobs-working-holidays/malaysia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/malaysia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/malaysia');
insert into url_map (url_from, url_to, date) values ('/jobs/maldives','/seasonal-jobs-working-holidays/maldives', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/maldives' where section_uri = (select section_uri from article_map where section_uri = '/jobs/maldives');
insert into url_map (url_from, url_to, date) values ('/jobs/malta','/seasonal-jobs-working-holidays/malta', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/malta' where section_uri = (select section_uri from article_map where section_uri = '/jobs/malta');
insert into url_map (url_from, url_to, date) values ('/jobs/mauritius','/seasonal-jobs-working-holidays/mauritius', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/mauritius' where section_uri = (select section_uri from article_map where section_uri = '/jobs/mauritius');
insert into url_map (url_from, url_to, date) values ('/jobs/mexico','/seasonal-jobs-working-holidays/mexico', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/mexico' where section_uri = (select section_uri from article_map where section_uri = '/jobs/mexico');
insert into url_map (url_from, url_to, date) values ('/jobs/mexico/cancun','/seasonal-jobs-working-holidays/mexico/cancun', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/mexico/cancun' where section_uri = (select section_uri from article_map where section_uri = '/jobs/mexico/cancun');
insert into url_map (url_from, url_to, date) values ('/jobs/mexico/mexico-city','/seasonal-jobs-working-holidays/mexico/mexico-city', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/mexico/mexico-city' where section_uri = (select section_uri from article_map where section_uri = '/jobs/mexico/mexico-city');
insert into url_map (url_from, url_to, date) values ('/jobs/middle-east','/seasonal-jobs-working-holidays/middle-east', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/middle-east' where section_uri = (select section_uri from article_map where section_uri = '/jobs/middle-east');
insert into url_map (url_from, url_to, date) values ('/jobs/myanmar','/seasonal-jobs-working-holidays/myanmar', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/myanmar' where section_uri = (select section_uri from article_map where section_uri = '/jobs/myanmar');
insert into url_map (url_from, url_to, date) values ('/jobs/nepal','/seasonal-jobs-working-holidays/nepal', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/nepal' where section_uri = (select section_uri from article_map where section_uri = '/jobs/nepal');
insert into url_map (url_from, url_to, date) values ('/jobs/netherlands','/seasonal-jobs-working-holidays/netherlands', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/netherlands' where section_uri = (select section_uri from article_map where section_uri = '/jobs/netherlands');
insert into url_map (url_from, url_to, date) values ('/jobs/new-zealand','/seasonal-jobs-working-holidays/new-zealand', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/new-zealand' where section_uri = (select section_uri from article_map where section_uri = '/jobs/new-zealand');
insert into url_map (url_from, url_to, date) values ('/jobs/nicaragua','/seasonal-jobs-working-holidays/nicaragua', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/nicaragua' where section_uri = (select section_uri from article_map where section_uri = '/jobs/nicaragua');
insert into url_map (url_from, url_to, date) values ('/jobs/north-america','/seasonal-jobs-working-holidays/north-america', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/north-america' where section_uri = (select section_uri from article_map where section_uri = '/jobs/north-america');
insert into url_map (url_from, url_to, date) values ('/jobs/norway','/seasonal-jobs-working-holidays/norway', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/norway' where section_uri = (select section_uri from article_map where section_uri = '/jobs/norway');
insert into url_map (url_from, url_to, date) values ('/jobs/oman','/seasonal-jobs-working-holidays/oman', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/oman' where section_uri = (select section_uri from article_map where section_uri = '/jobs/oman');
insert into url_map (url_from, url_to, date) values ('/jobs/panama','/seasonal-jobs-working-holidays/panama', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/panama' where section_uri = (select section_uri from article_map where section_uri = '/jobs/panama');
insert into url_map (url_from, url_to, date) values ('/jobs/paraguay','/seasonal-jobs-working-holidays/paraguay', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/paraguay' where section_uri = (select section_uri from article_map where section_uri = '/jobs/paraguay');
insert into url_map (url_from, url_to, date) values ('/jobs/peru','/seasonal-jobs-working-holidays/peru', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/peru' where section_uri = (select section_uri from article_map where section_uri = '/jobs/peru');
insert into url_map (url_from, url_to, date) values ('/jobs/philippines','/seasonal-jobs-working-holidays/philippines', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/philippines' where section_uri = (select section_uri from article_map where section_uri = '/jobs/philippines');
insert into url_map (url_from, url_to, date) values ('/jobs/poland','/seasonal-jobs-working-holidays/poland', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/poland' where section_uri = (select section_uri from article_map where section_uri = '/jobs/poland');
insert into url_map (url_from, url_to, date) values ('/jobs/portugal','/seasonal-jobs-working-holidays/portugal', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/portugal' where section_uri = (select section_uri from article_map where section_uri = '/jobs/portugal');
insert into url_map (url_from, url_to, date) values ('/jobs/romania','/seasonal-jobs-working-holidays/romania', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/romania' where section_uri = (select section_uri from article_map where section_uri = '/jobs/romania');
insert into url_map (url_from, url_to, date) values ('/jobs/russia','/seasonal-jobs-working-holidays/russia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/russia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/russia');
insert into url_map (url_from, url_to, date) values ('/jobs/saudi_arabia','/seasonal-jobs-working-holidays/saudi_arabia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/saudi_arabia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/saudi_arabia');
insert into url_map (url_from, url_to, date) values ('/jobs/singapore','/seasonal-jobs-working-holidays/singapore', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/singapore' where section_uri = (select section_uri from article_map where section_uri = '/jobs/singapore');
insert into url_map (url_from, url_to, date) values ('/jobs/south-africa','/seasonal-jobs-working-holidays/south-africa', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/south-africa' where section_uri = (select section_uri from article_map where section_uri = '/jobs/south-africa');
insert into url_map (url_from, url_to, date) values ('/jobs/south-america','/seasonal-jobs-working-holidays/south-america', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/south-america' where section_uri = (select section_uri from article_map where section_uri = '/jobs/south-america');
insert into url_map (url_from, url_to, date) values ('/jobs/spain','/seasonal-jobs-working-holidays/spain', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/alicante','/seasonal-jobs-working-holidays/spain/alicante', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/alicante' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/alicante');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/barcelona','/seasonal-jobs-working-holidays/spain/barcelona', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/barcelona' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/barcelona');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/benidorm','/seasonal-jobs-working-holidays/spain/benidorm', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/benidorm' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/benidorm');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/ibiza','/seasonal-jobs-working-holidays/spain/ibiza', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/ibiza' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/ibiza');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/lanzarote','/seasonal-jobs-working-holidays/spain/lanzarote', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/lanzarote' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/lanzarote');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/madrid','/seasonal-jobs-working-holidays/spain/madrid', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/madrid' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/madrid');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/magaluf','/seasonal-jobs-working-holidays/spain/magaluf', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/magaluf' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/magaluf');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/majorca','/seasonal-jobs-working-holidays/spain/majorca', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/majorca' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/majorca');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/mallorca','/seasonal-jobs-working-holidays/spain/mallorca', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/mallorca' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/mallorca');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/seville','/seasonal-jobs-working-holidays/spain/seville', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/seville' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/seville');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/tenerife','/seasonal-jobs-working-holidays/spain/tenerife', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/tenerife' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/tenerife');
insert into url_map (url_from, url_to, date) values ('/jobs/spain/valencia','/seasonal-jobs-working-holidays/spain/valencia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/spain/valencia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/spain/valencia');
insert into url_map (url_from, url_to, date) values ('/jobs/sri-lanka','/seasonal-jobs-working-holidays/sri-lanka', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/sri-lanka' where section_uri = (select section_uri from article_map where section_uri = '/jobs/sri-lanka');
insert into url_map (url_from, url_to, date) values ('/jobs/sweden','/seasonal-jobs-working-holidays/sweden', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/sweden' where section_uri = (select section_uri from article_map where section_uri = '/jobs/sweden');
insert into url_map (url_from, url_to, date) values ('/jobs/switzerland','/seasonal-jobs-working-holidays/switzerland', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/switzerland' where section_uri = (select section_uri from article_map where section_uri = '/jobs/switzerland');
insert into url_map (url_from, url_to, date) values ('/jobs/taiwan','/seasonal-jobs-working-holidays/taiwan', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/taiwan' where section_uri = (select section_uri from article_map where section_uri = '/jobs/taiwan');
insert into url_map (url_from, url_to, date) values ('/jobs/thailand','/seasonal-jobs-working-holidays/thailand', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/thailand' where section_uri = (select section_uri from article_map where section_uri = '/jobs/thailand');
insert into url_map (url_from, url_to, date) values ('/jobs/turkey','/seasonal-jobs-working-holidays/turkey', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/turkey' where section_uri = (select section_uri from article_map where section_uri = '/jobs/turkey');
insert into url_map (url_from, url_to, date) values ('/jobs/ukraine','/seasonal-jobs-working-holidays/ukraine', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/ukraine' where section_uri = (select section_uri from article_map where section_uri = '/jobs/ukraine');
insert into url_map (url_from, url_to, date) values ('/jobs/united_arab_emirates','/seasonal-jobs-working-holidays/united_arab_emirates', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united_arab_emirates' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united_arab_emirates');
insert into url_map (url_from, url_to, date) values ('/jobs/united-kingdom','/seasonal-jobs-working-holidays/united-kingdom', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-kingdom' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-kingdom');
insert into url_map (url_from, url_to, date) values ('/jobs/united-kingdom/bournemouth','/seasonal-jobs-working-holidays/united-kingdom/bournemouth', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-kingdom/bournemouth' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-kingdom/bournemouth');
insert into url_map (url_from, url_to, date) values ('/jobs/united-kingdom/isles-of-scilly','/seasonal-jobs-working-holidays/united-kingdom/isles-of-scilly', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-kingdom/isles-of-scilly' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-kingdom/isles-of-scilly');
insert into url_map (url_from, url_to, date) values ('/jobs/united-kingdom/london','/seasonal-jobs-working-holidays/united-kingdom/london', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-kingdom/london' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-kingdom/london');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states','/seasonal-jobs-working-holidays/united-states', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/alabama','/seasonal-jobs-working-holidays/united-states/alabama', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/alabama' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/alabama');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/alaska','/seasonal-jobs-working-holidays/united-states/alaska', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/alaska' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/alaska');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/arizona','/seasonal-jobs-working-holidays/united-states/arizona', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/arizona' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/arizona');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/arkansas','/seasonal-jobs-working-holidays/united-states/arkansas', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/arkansas' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/arkansas');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/california','/seasonal-jobs-working-holidays/united-states/california', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/california' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/california');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/colorado','/seasonal-jobs-working-holidays/united-states/colorado', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/colorado' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/colorado');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/connecticut','/seasonal-jobs-working-holidays/united-states/connecticut', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/connecticut' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/connecticut');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/delaware','/seasonal-jobs-working-holidays/united-states/delaware', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/delaware' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/delaware');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/florida','/seasonal-jobs-working-holidays/united-states/florida', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/florida' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/florida');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/georgia','/seasonal-jobs-working-holidays/united-states/georgia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/georgia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/georgia');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/hawaii','/seasonal-jobs-working-holidays/united-states/hawaii', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/hawaii' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/hawaii');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/idaho','/seasonal-jobs-working-holidays/united-states/idaho', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/idaho' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/idaho');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/illinois','/seasonal-jobs-working-holidays/united-states/illinois', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/illinois' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/illinois');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/indiana','/seasonal-jobs-working-holidays/united-states/indiana', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/indiana' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/indiana');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/iowa','/seasonal-jobs-working-holidays/united-states/iowa', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/iowa' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/iowa');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/kansas','/seasonal-jobs-working-holidays/united-states/kansas', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/kansas' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/kansas');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/kentucky','/seasonal-jobs-working-holidays/united-states/kentucky', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/kentucky' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/kentucky');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/louisiana','/seasonal-jobs-working-holidays/united-states/louisiana', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/louisiana' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/louisiana');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/maine','/seasonal-jobs-working-holidays/united-states/maine', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/maine' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/maine');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/maryland','/seasonal-jobs-working-holidays/united-states/maryland', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/maryland' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/maryland');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/massachusetts','/seasonal-jobs-working-holidays/united-states/massachusetts', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/massachusetts' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/massachusetts');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/michigan','/seasonal-jobs-working-holidays/united-states/michigan', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/michigan' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/michigan');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/minnesota','/seasonal-jobs-working-holidays/united-states/minnesota', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/minnesota' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/minnesota');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/mississippi','/seasonal-jobs-working-holidays/united-states/mississippi', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/mississippi' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/mississippi');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/missouri','/seasonal-jobs-working-holidays/united-states/missouri', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/missouri' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/missouri');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/montana','/seasonal-jobs-working-holidays/united-states/montana', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/montana' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/montana');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/nebraska','/seasonal-jobs-working-holidays/united-states/nebraska', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/nebraska' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/nebraska');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/nevada','/seasonal-jobs-working-holidays/united-states/nevada', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/nevada' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/nevada');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/new-hampshire','/seasonal-jobs-working-holidays/united-states/new-hampshire', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/new-hampshire' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/new-hampshire');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/new-jersey','/seasonal-jobs-working-holidays/united-states/new-jersey', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/new-jersey' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/new-jersey');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/new-mexico','/seasonal-jobs-working-holidays/united-states/new-mexico', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/new-mexico' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/new-mexico');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/new-york','/seasonal-jobs-working-holidays/united-states/new-york', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/new-york' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/new-york');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/north-carolina','/seasonal-jobs-working-holidays/united-states/north-carolina', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/north-carolina' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/north-carolina');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/north-dakota','/seasonal-jobs-working-holidays/united-states/north-dakota', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/north-dakota' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/north-dakota');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/ohio','/seasonal-jobs-working-holidays/united-states/ohio', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/ohio' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/ohio');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/oklahoma','/seasonal-jobs-working-holidays/united-states/oklahoma', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/oklahoma' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/oklahoma');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/oregon','/seasonal-jobs-working-holidays/united-states/oregon', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/oregon' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/oregon');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/pennsylvania','/seasonal-jobs-working-holidays/united-states/pennsylvania', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/pennsylvania' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/pennsylvania');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/rhode-island','/seasonal-jobs-working-holidays/united-states/rhode-island', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/rhode-island' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/rhode-island');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/south-carolina','/seasonal-jobs-working-holidays/united-states/south-carolina', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/south-carolina' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/south-carolina');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/south-dakota','/seasonal-jobs-working-holidays/united-states/south-dakota', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/south-dakota' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/south-dakota');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/tennessee','/seasonal-jobs-working-holidays/united-states/tennessee', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/tennessee' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/tennessee');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/texas','/seasonal-jobs-working-holidays/united-states/texas', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/texas' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/texas');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/utah','/seasonal-jobs-working-holidays/united-states/utah', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/utah' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/utah');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/vermont','/seasonal-jobs-working-holidays/united-states/vermont', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/vermont' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/vermont');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/virginia','/seasonal-jobs-working-holidays/united-states/virginia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/virginia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/virginia');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/washington','/seasonal-jobs-working-holidays/united-states/washington', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/washington' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/washington');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/west-virginia','/seasonal-jobs-working-holidays/united-states/west-virginia', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/west-virginia' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/west-virginia');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/wisconsin','/seasonal-jobs-working-holidays/united-states/wisconsin', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/wisconsin' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/wisconsin');
insert into url_map (url_from, url_to, date) values ('/jobs/united-states/wyoming','/seasonal-jobs-working-holidays/united-states/wyoming', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/united-states/wyoming' where section_uri = (select section_uri from article_map where section_uri = '/jobs/united-states/wyoming');
insert into url_map (url_from, url_to, date) values ('/jobs/uruguay','/seasonal-jobs-working-holidays/uruguay', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/uruguay' where section_uri = (select section_uri from article_map where section_uri = '/jobs/uruguay');
insert into url_map (url_from, url_to, date) values ('/jobs/zimbabwe','/seasonal-jobs-working-holidays/zimbabwe', now()::timestamp);
update article_map set section_uri = '/seasonal-jobs-working-holidays/zimbabwe' where section_uri = (select section_uri from article_map where section_uri = '/jobs/zimbabwe');
