DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/october/volunteer-hiv-aids-projects-abroad');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/october/volunteer-hiv-aids-projects-abroad');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/october/volunteer-hiv-aids-projects-abroad';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/summer-camp-jobs-usa-what-company-to-apply-with');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/summer-camp-jobs-usa-what-company-to-apply-with');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/november/summer-camp-jobs-usa-what-company-to-apply-with';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-parents-advice');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-parents-advice');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-parents-advice';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/tefl-abroad-china-disney-english-programs-esl-jobs-asia');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/tefl-abroad-china-disney-english-programs-esl-jobs-asia');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/november/tefl-abroad-china-disney-english-programs-esl-jobs-asia';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-work-job-hunting-advice');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-work-job-hunting-advice');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/travel-gap-year-work-job-hunting-advice';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/grown-up-gap-year-30-35-career-break-volunteer-work-travel');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/grown-up-gap-year-30-35-career-break-volunteer-work-travel');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/august/grown-up-gap-year-30-35-career-break-volunteer-work-travel';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/travel-safety-tips-gap-year-information');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/travel-safety-tips-gap-year-information');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/august/travel-safety-tips-gap-year-information';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-advice-guidance-ideas-volunteer-abroad');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-advice-guidance-ideas-volunteer-abroad');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/travel-gap-year-advice-guidance-ideas-volunteer-abroad';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/august/take-a-constructive-gap-year');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/august/take-a-constructive-gap-year');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/august/take-a-constructive-gap-year';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/august/not-going-to-university-take-a-gap-year');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/august/not-going-to-university-take-a-gap-year');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/august/not-going-to-university-take-a-gap-year';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/july/2012-gap-year');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/july/2012-gap-year');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/july/2012-gap-year';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/june/gap-year-programmes-for-students');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/june/gap-year-programmes-for-students');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/june/gap-year-programmes-for-students';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/june/gap-year-programmes-for-graduates');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/june/gap-year-programmes-for-graduates');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/june/gap-year-programmes-for-graduates';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/may/thinking-about-taking-a-gap-year');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/may/thinking-about-taking-a-gap-year');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/may/thinking-about-taking-a-gap-year';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/april/gap-year-information-evenings');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/april/gap-year-information-evenings');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/april/gap-year-information-evenings';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-trips-parents-advice');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-trips-parents-advice');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-trips-parents-advice';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-holidays');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-holidays');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/january/gap-year-holidays';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/february/plan-a-gap-year-instead-of-university');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/february/plan-a-gap-year-instead-of-university');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/february/plan-a-gap-year-instead-of-university';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/march/gap-year-before-or-after-uni-when-to-travel-abroad');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/march/gap-year-before-or-after-uni-when-to-travel-abroad');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/march/gap-year-before-or-after-uni-when-to-travel-abroad';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/april/fco-gap-year');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/april/fco-gap-year');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/april/fco-gap-year';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year planning-advice-guidance-volunteering-overseas');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year planning-advice-guidance-volunteering-overseas');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/travel-gap-year planning-advice-guidance-volunteering-overseas';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/united-kingdom-volunteering-england-wales-scotland-northern-ireland-voluntary-work');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/united-kingdom-volunteering-england-wales-scotland-northern-ireland-voluntary-work');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/august/united-kingdom-volunteering-england-wales-scotland-northern-ireland-voluntary-work';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-travel-positive-outlook-for-2011-gap-years');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-travel-positive-outlook-for-2011-gap-years');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-travel-positive-outlook-for-2011-gap-years';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/learn-a-new-language-russian-basic-phrases-courses-travel');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/learn-a-new-language-russian-basic-phrases-courses-travel');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/august/learn-a-new-language-russian-basic-phrases-courses-travel';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/gap-year-travel-programmes-volunteer-work-placements-overseas-volunteering-projects-abroad');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/gap-year-travel-programmes-volunteer-work-placements-overseas-volunteering-projects-abroad');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/august/gap-year-travel-programmes-volunteer-work-placements-overseas-volunteering-projects-abroad';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/2010-top-travel-destinations-lonely-planet');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/august/2010-top-travel-destinations-lonely-planet');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/august/2010-top-travel-destinations-lonely-planet';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/june/volunteer-abroad-africa-voluntary-teaching-projects-mombasa-kenya');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/june/volunteer-abroad-africa-voluntary-teaching-projects-mombasa-kenya');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/june/volunteer-abroad-africa-voluntary-teaching-projects-mombasa-kenya';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/europe-paid-hospitality-work-experience-spain-italy');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/europe-paid-hospitality-work-experience-spain-italy');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/europe-paid-hospitality-work-experience-spain-italy';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-advice');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-advice');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-advice';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-alternatives-to-university-overseas-work-voluntary-projects-year-out');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-alternatives-to-university-overseas-work-voluntary-projects-year-out');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/travel-gap-year-alternatives-to-university-overseas-work-voluntary-projects-year-out';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/october/gapyear-travel-adventure-volunteer-study-teach-work-internship-study-abroad');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/october/gapyear-travel-adventure-volunteer-study-teach-work-internship-study-abroad');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/october/gapyear-travel-adventure-volunteer-study-teach-work-internship-study-abroad';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/taking-a-gap-year-before-medical-school');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/taking-a-gap-year-before-medical-school');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/taking-a-gap-year-before-medical-school';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/gap-year-2011');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/gap-year-2011');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/november/gap-year-2011';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-travel-graduates-facing-a-tough-employment-market-choose-gap-year-route-instead');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-travel-graduates-facing-a-tough-employment-market-choose-gap-year-route-instead');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-travel-graduates-facing-a-tough-employment-market-choose-gap-year-route-instead';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-to-take-a-gap-year-or-not-year-out-advice');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-to-take-a-gap-year-or-not-year-out-advice');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/travel-to-take-a-gap-year-or-not-year-out-advice';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-culture-shock-advice');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/september/travel-gap-year-culture-shock-advice');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/september/travel-gap-year-culture-shock-advice';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-travel-abroad-programs-language-courses-overseas');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-travel-abroad-programs-language-courses-overseas');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-travel-abroad-programs-language-courses-overseas';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-volunteer-travel-combination-programs');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-volunteer-travel-combination-programs');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-volunteer-travel-combination-programs';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/march/humanitarian-refugee-volunteer-gap-year-work-in-africa');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/march/humanitarian-refugee-volunteer-gap-year-work-in-africa');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/march/humanitarian-refugee-volunteer-gap-year-work-in-africa';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/february/humanitarian-gap-year-work-united-nations-peacekeeping-training-programmes');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/february/humanitarian-gap-year-work-united-nations-peacekeeping-training-programmes');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/february/humanitarian-gap-year-work-united-nations-peacekeeping-training-programmes';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/february/volunteer-humanitarian-gap-year-programs-abroad');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/february/volunteer-humanitarian-gap-year-programs-abroad');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/february/volunteer-humanitarian-gap-year-programs-abroad';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-work-and-travel-programs-around-the-world');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-work-and-travel-programs-around-the-world');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-work-and-travel-programs-around-the-world';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-jobs-abroad-working-holidays-2013');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-jobs-abroad-working-holidays-2013');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/january/gap-year-jobs-abroad-working-holidays-2013';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/gap-year-working-holidays-abroad-australia-canada-new-zealand-usa-jobs');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/november/gap-year-working-holidays-abroad-australia-canada-new-zealand-usa-jobs');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/november/gap-year-working-holidays-abroad-australia-canada-new-zealand-usa-jobs';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-hospitality-work-experience-jobs-abroad');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-hospitality-work-experience-jobs-abroad');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/january/gap-year-hospitality-work-experience-jobs-abroad';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-live-and-work-overseas');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2011/january/gap-year-live-and-work-overseas');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2011/january/gap-year-live-and-work-overseas';
DELETE from article_link where a1 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-work-abroad-australia-canada-new-zealand-usa-working-holiday-jobs');
DELETE from article_link where a2 = (select article_id from article_map where website_id = 1 and section_uri = '/news/2010/december/gap-year-work-abroad-australia-canada-new-zealand-usa-working-holiday-jobs');
DELETE FROM article_map WHERE website_id = 1 AND section_uri = '/news/2010/december/gap-year-work-abroad-australia-canada-new-zealand-usa-working-holiday-jobs';
