DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/february/volunteer-childcare-and-teaching-projects-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/volunteer-childcare-and-teaching-projects-in-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/april/india-himalayan-community-volunteer-programme';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/india-himalayan-community-volunteer-programme','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/february/india-slum-volunteer-projects';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/india-slum-volunteer-projects','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/february/india-healthcare-volunteer-projects';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/india-healthcare-volunteer-projects','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/july/volunteer-in-incredible-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/volunteer-in-incredible-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/december/a-guide-to-volunteering-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/a-guide-to-volunteering-in-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/july/care-volunteer-projects-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/care-volunteer-projects-in-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/july/teaching-volunteer-projects-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/teaching-volunteer-projects-in-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/july/care-volunteer-projects-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/care-volunteer-projects-in-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/july/india-volunteer-projects-in-trivandrum-and-kerala';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/india-volunteer-projects-in-trivandrum-and-kerala','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/may/family-volunteer-projects-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/may/family-volunteer-projects-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/february/india-summer-volunteer-programs';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/india-summer-volunteer-programs','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/december/volunteer-india-2011-2012-orphanages-healthcare-womens-empowerment-teaching-childcare-community-programs';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/volunteer-india-2011-2012-orphanages-healthcare-womens-empowerment-teaching-childcare-community-programs','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/march/india-volunteer-and-travel';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/india-volunteer-and-travel','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/november/volunteer-abroad-india-vetinary-work-experience-animal-conservation-projects';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/volunteer-abroad-india-vetinary-work-experience-animal-conservation-projects','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/august/view-volunteer-trips-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/august/view-volunteer-trips-in-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/november/internships-abroad-asia-work-experience-mumbai-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/internships-abroad-asia-work-experience-mumbai-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/february/india-travel-internship';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/india-travel-internship','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/july/work-experience-internships-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/work-experience-internships-in-india','/travel/india/volunteer-in-india',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/february/india-travel-taj-mahol-trips-and-volunteering';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/india-travel-taj-mahol-trips-and-volunteering','/travel/india',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/guyana/tours-in-guyana','/travel/guyana',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/guyana/volunteer-in-guyana','/travel/guyana',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/uruguay/tours-in-uruguay','/travel/uruguay',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/uruguay/volunteer-in-uruguay','/travel/uruguay',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/venezuela/volunteer-in-venezuela','/travel/venezuela',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/venezuela/tours-in-venezuela','/travel/venezuela',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/paraguay/tours-in-paraguay','/travel/paraguay',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/paraguay/volunteer-in-paraguay','/travel/paraguay',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bolivia/tours-in-bolivia','/travel/bolivia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bolivia/volunteer-in-bolivia','/travel/bolivia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bolivia/tours-in-chile','/travel/chile',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/colombia/tours-in-colombia','/travel/colombia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/ecuador/tours-in-ecuador','/travel/ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/ecuador-and-galapagos-volunteer-trips-february-discounted-prices','/travel/ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/volunteer-at-a-summer-camp-in-ecuador','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/ecuador-and-galapagos-volunteering-programs','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/ecuador-rainforest-and-wildlife-volunteer-projects','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/ecuador-volunteer-opportunities','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/volunteer-projects-in-ecuador','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/ecuador-volunteer-opportunities','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/learn-spanish-and-volunteer-in-ecuador','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/ecuador-and-galapagos-volunteer-trips-february-discounted-prices','/travel/ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/ecuador-and-galapagos-islands-holiday-packages','/travel/ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/ecuador-and-galapagos-volunteer-adventure-trips','/travel/ecuador/volunteer-in-ecuador',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/may/family-volunteer-projects-brazil','/travel/brazil/volunteer-in-brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/search/volunteer-in-rio-de-janeiro','/travel/brazil/volunteer-in-brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/search/volunteer-in-the-amazon','/travel/brazil/volunteer-in-brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/june/brazil-favela-volunteer-projects','/travel/brazil/volunteer-in-brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/search/volunteer-in-bahia','/travel/brazil/volunteer-in-brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/november/volunteer-programs-in-rio-and-san-paulo-brazil','/travel/brazil/volunteer-in-brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/september/brazil-meaningful-travel-opportunities','/travel/brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/july/brazil-adventure-holidays','/travel/brazil',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/tanzania/tours-in-tanzania','/travel/tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/medical-healthcare-internships-in-tanzania-africa','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/tanzania-volunteer-teaching-programs','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/medical-volunteer-programs-in-tanzania','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/africa-volunteer-and-teach-in-tanzania','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/volunteer-projects-in-tanzania','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/ngo-volunteer-projects-in-tanzania-africa','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/volunteer-projects-in-tanzania','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/september/travel-tanzania-medical-health-care-volunteer-work-gap-year-projects','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/tanzania-volunteer-projectsquickly-becoming-africas-number-1-destination-for-volunteers','/travel/tanzania/volunteer-in-tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/kenya/tours-in-kenya','/travel/kenya',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/august/volunteer-with-lions-in-south-africa','/search/volunteer-lions',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/south-africa-volunteer-with-lions','/search/volunteer-lions',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/volunteer-abroad-south-africa-animal-lion-conservation-programmes','/search/volunteer-lions',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/travel-abroad-south-africa-top-10-tourist-attractions','/travel/south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/june/law-human-rights-volunteer-work-in-south-africa','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/wildlife-volunteer-holidays-in-south-africa','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/march/visito-learn-to-surf-in-south-africa-overland-adventure-tour-southern-africa','/travel/south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/south-africa-township-volunteer-programs','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/travel-and-volunteer-in-south-africa-teaching-english','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/may/family-volunteer-projects-south-africa','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/sports-coaching-volunteer-projects-south-africa','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/south-africa-volunteer-conservation-and-community-projects','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/october/africa-wild-coast-horse-riding-holiday-south-africa-horse-trails-safaris-farm-riding-vacation','/activity/horse-riding-holidays',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/south-africa-wildlife-film-making-courses','/activity/photography-holidays',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/august/volunteer-with-lions-in-zimbabwe','/search/volunteer-lions',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/zimbabwe-wildlife-conservation','/travel/zimbabwe',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/zimbabwe-black-rhino-conservation-volunteer-programs','/travel/zimbabwe',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/zimbabwe-elephant-volunteer-programs','/travel/zimbabwe',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/zimbabwe/tours-in-zimbabwe','/travel/zimbabwe',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/zimbabwe/volunteer-in-zimbabwe','/travel/zimbabwe',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/search/galapagos-islands-work';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/search/galapagos-islands-work','/travel/galapagos-islands',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/galapagos-islands/working-holidays-in-galapagos-islands','/travel/galapagos-islands',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/galapagos-islands/teach-in-galapagos-islands','/travel/galapagos-islands',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/search/galapagos-islands-teach';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/search/galapagos-islands-teach','/travel/galapagos-islands',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/galapagos-islands/tours-in-galapagos-islands','/travel/galapagos-islands',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/costa-rica/tours-in-costa-rica','/travel/costa-rica',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/travel-and-volunteer-holidays-in-costa-rica','/travel/costa-rica/volunteer-in-costa-rica',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/july/costa-rica-adventure-travel','/travel/costa-rica',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/view-study-and-volunteer-travel-programs-in-costa-rica','/travel/costa-rica/volunteer-in-costa-rica',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/costa-rica-travel-and-teach-english','/travel/costa-rica/volunteer-in-costa-rica',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/costa-rica/teach-in-costa-rica','/travel/costa-rica/volunteer-in-costa-rica',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/france/paris/best-things-to-see-and-do-in-paris','/travel/france/paris',0,now()::timestamp);
UPDATE url_map SET url_to ='/travel/france/paris' WHERE sid = 0 and url_to ='/travel/france/paris/cheap-accommodation-hotels-and-hostels-in-paris';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/france/paris/cheap-accommodation-hotels-and-hostels-in-paris','/travel/france/paris',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/france/paris/cheap-flights-to-paris','/travel/france/paris',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/france/paris/travel-tips-paris','/travel/france/paris',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/july/family-adventure-tours-to-egypt-jordan-and-morocco','/continent/africa',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/argentina/buenos-aires/top-5-things-to-do-in-buenos-aires','/travel/argentina/buenos-aires',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/june/travel-recommendations-for-the-best-beaches-in-the-world';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/june/travel-recommendations-for-the-best-beaches-in-the-world','/travel-tips/the-best-beaches-in-the-world-to-visit',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/volunteer-abroad-fiji-south-pacific-voluntary-work-programs','/travel/fiji',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/november/african-volunteer-adventure-in-botswana','/travel/botswana',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/bolivia-volunteer-work','/travel/bolivia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/africa-gap-year-volunteer-projects','/continent/africa/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/january/why-do-i-need-to-pay-to-volunteer-in-india','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/volunteering-overseas-why-pay-to-volunteer','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/start-planning-a-volunteer-trip-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/may/find-volunteering-opportunities-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/march/find-safe-and-structured-volunteering-programs-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/march/travel-and-volunteer-in-india-sri-lanka-and-nepal','/continent/asia/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/travel-abroad-serengeti-national-park-safari-tours-africa','/activity/safari-tours',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/travel-abroad-tanzania-safari-tours-africa','/travel/tanzania',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/need-help-choosing-an-african-safari','/activity/safari-tours',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/find-inspirational-voluntary-projects-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/volunteer-vacations-in-africa-asia-and-latin-america','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/june/volunteer-overseas-and-make-a-difference','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/june/volunteer-around-the-world','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/holiday-volunteer-work','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/the-best-volunteer-travel-programs-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/october/skilled-volunteer-positions-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/december/discounted-africa-and-latin-america-volunteer-travel-programs','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/volunteer-abroad-skilled-volunteering-jobs-overseas','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/volunteer-abroad-skilled-volunteering-jobs-overseas','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/december/discounted-africa-and-latin-america-volunteer-travel-programs','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/october/skilled-volunteer-positions-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/the-best-volunteer-travel-programs-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/work-abroad-china-tefl-teaching-jobs-english-trainers-disney','/travel/china',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2009/destination-china','/travel/china',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2012/worldwide-volunteer-holidays','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2011/asia-volunteer-work-teach-travel-tours-gap-year','/continent/asia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2012/worldwide-adventure-tours','/activity/travel/tour',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2009/community-projects','/activity/community-projects',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2011/summer-work-and-travel-usa','/travel/united-states',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2010/galapagos-islands-travel-gap-year-conservation-volunteering','/travel/galapagos-islands',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/features/2009/conservation','/activity/conservation-projects',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/peru-amazon-rainforest-conservation-volunteer-opportunities','/continent/south-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/sea-horse-conservation-volunteer-projects-in-cambodia','/travel/cambodia/volunteer-in-cambodia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/conservation-volunteer-projects-in-vietnam','/travel/vietnam/volunteer-in-vietnam',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/vietnam-volunteer-adventure-holiday','/travel/vietnam/volunteer-in-vietnam',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/a-guide-to-volunteering-in-vietnam','/travel/vietnam/volunteer-in-vietnam',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/april/volunteer-opportunities-abroad-for-seniors','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/volunteering-abroad-while-studying-in-school-or-college','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/may/conservation-and-community-project-in-the-amazon-of-peru','/travel/peru/volunteer-in-peru',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/november/south-america-volunteer-teaching','/continent/south-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/november/south-america-dental-volunteer-projects','/continent/south-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/volunteer-holidays-in-south-and-central-america','/continent/south-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/volunteer-holidays-in-latin-america','/continent/south-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/summer-conservation-volunteer-opportunities-in-central-america','/continent/central-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/central-america-volunteer-programs','/continent/central-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/central-america-volunteer-opportunities','/continent/central-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/november/dental-volunteer-projects-central-america','/continent/central-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/november/spiritual-volunteer-holidays-in-central-america','/continent/central-america/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/dental-volunteer-programs-in-asia','/continent/asia/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/gain-work-experience-by-volunteering-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/ngo-volunteer-opportunities','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/april/find-free-volunteer-programs-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/november/cheap-and-affordable-volunteer-programs-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/affordable-volunteering-opportunities-in-africa-asia-latin-america','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/april/ideas-for-volunteer-holidays-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/budget-volunteering-programs-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/january/find-free-volunteer-programs-overseas','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/travel-and-volunteer-abroad-thailand-ultimate-adventure-voluntary-work-trip-asia','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/thailand-volunteer-adventure-holidays','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/thailand-summer-volunteer-opportunities','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/thailand-wildlife-conservation-programs','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/volunteer-projects-in-thailand','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/thailand-volunteer-conservation-projects','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/april/thailand-volunteer-holiday-ideas','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/east-timor/tours-in-east-timor','/travel/east-timor',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/east-timor/tours-in-east-timor','/travel/east-timor',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/cambodia/tours-in-cambodia','/travel/cambodia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/brunei/tours-in-brunei','/travel/brunei',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/brunei/volunteer-in-brunei','/travel/brunei',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bhutan/tours-in-bhutan','/travel/bhutan',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bhutan/volunteer-in-bhutan','/travel/bhutan',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bangladesh/tours-in-bangladesh','/travel/bangladesh',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bangladesh/volunteer-in-bangladesh','/travel/bangladesh',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/myanmar/volunteer-in-myanmar','/travel/myanmar',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/myanmar/tours-in-myanmar','/travel/myanmar',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/pakistan/tours-in-pakistan','/travel/pakistan',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/pakistan/volunteer-in-pakistan','/travel/pakistan',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/mongolia/tours-in-mongolia','/travel/mongolia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/mongolia/volunteer-in-mongolia','/travel/mongolia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/maldives/tours-in-maldives','/travel/maldives',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/maldives/volunteer-in-maldives','/travel/maldives',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/lebanon/tours-in-lebanon','/travel/lebanon',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/lebanon/volunteer-in-lebanon','/travel/lebanon',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/jordan/tours-in-jordan','/travel/jordan',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/jordan/volunteer-in-jordan','/travel/jordan',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/iran/tours-in-iran','/travel/iran',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/iran/volunteer-in-iran','/travel/iran',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/hong-kong/tours-in-hong-kong','/travel/hong-kong',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/hong-kong/volunteer-in-hong-kong','/travel/hong-kong',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/korea/tours-in-korea','/travel/korea',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/korea/volunteer-in-korea','/travel/korea',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/taiwan/volunteer-in-taiwan','/travel/taiwan',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/taiwan/tours-in-taiwan','/travel/taiwan',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/december/volunteer-abroad-south-africa-gap-year-wildlife-conservation-voluntary-work-programs';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/december/volunteer-abroad-south-africa-gap-year-wildlife-conservation-voluntary-work-programs','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/february/south-africa-conservation-volunteer-projects';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/south-africa-conservation-volunteer-projects','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/april/south-africa-game-ranger-volunteer-course';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/south-africa-game-ranger-volunteer-course','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/january/south-africa-adventure-holidays';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/january/south-africa-adventure-holidays','/travel/south-africa',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/january/south-africa-volunteer-travel-knysna-and-the-garden-route';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/january/south-africa-volunteer-travel-knysna-and-the-garden-route','/travel/south-africa',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/october/volunteer-abroad-cheetah-lion-sable-antelope-animal-conservation-projects-south-africa';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/october/volunteer-abroad-cheetah-lion-sable-antelope-animal-conservation-projects-south-africa','/travel/south-africa/volunteer-in-south-africa',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/travel/south-africa/tours-in-south-africa';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/south-africa/tours-in-south-africa','/travel/south-africa',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2010/august/volunteer-with-lion-cubs-in-south-africa';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2010/august/volunteer-with-lion-cubs-in-south-africa','/search/volunteer-lions',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/april/volunteer-lions-africa';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/volunteer-lions-africa','/search/volunteer-lions',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/august/lion-cub-volunteer-programs';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/lion-cub-volunteer-programs','/search/volunteer-lions',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/february/bear-conservation-projects';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/bear-conservation-projects','/search/volunteer-bears',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/march/childcare-and-orphanage-volunteer-work-projects';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/march/childcare-and-orphanage-volunteer-work-projects','/activity/orphanage-work',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/january/volunteer-abroad-orphanages-childcare-schools';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/january/volunteer-abroad-orphanages-childcare-schools','/activity/orphanage-work',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/april/argentina-orphanage-volunteer-opportunities';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/argentina-orphanage-volunteer-opportunities','/activity/orphanage-work',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/july/orphanage-volunteer-projects-in-tanzania-africa';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/july/orphanage-volunteer-projects-in-tanzania-africa','/activity/orphanage-work',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/february/orphanage-volunteer-projects-in-india';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/orphanage-volunteer-projects-in-india','/activity/orphanage-work',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2012/march/sri-lanka-orphanage-volunteer-work';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/march/sri-lanka-orphanage-volunteer-work','/activity/orphanage-work',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/april/orphanage-volunteer-projects-in-laos';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/orphanage-volunteer-projects-in-laos','/activity/orphanage-work',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/march/inspirational-volunteer-projects-in-argentina';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/inspirational-volunteer-projects-in-argentina','/travel/argentina/volunteer-in-argentina',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/april/argentina-volunteer-animals';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/argentina-volunteer-animals','/travel/argentina/volunteer-in-argentina',0,now()::timestamp);
DELETE FROM url_map WHERE sid = 0 AND url_from ='/news/2011/august/animal-welfare-volunteer-work';
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/animal-welfare-volunteer-work','/activity/animal-volunteer-projects',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/november/thailand-and-burma-volunteer-opportunities','/travel/myanmar',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/thailand-elephant-volunteer-work','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/august/thailand-football-coaching-volunteer-jobs','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/march/thailand-4-week-summer-volunteer-opportunities','/travel/thailand/volunteer-in-thailand',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2012/february/volunteer-teaching-english-programs-in-siem-reap-cambodia','/travel/cambodia/volunteer-in-cambodia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/august/angkor-wat-cambodia-childcare-volunteer-projects','/travel/cambodia/volunteer-in-cambodia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/medical-volunteer-projects-in-cambodia','/travel/cambodia/volunteer-in-cambodia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/human-rights-volunteer-projects-in-cambodia','/travel/cambodia/volunteer-in-cambodia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/april/volunteer-programs-in-cambodia','/travel/cambodia/volunteer-in-cambodia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/sri-lanka/tours-in-sri-lanka','/travel/sri-lanka',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/may/volunteer-and-teach-in-sri-lanka','/travel/sri-lanka/volunteer-in-sri-lanka',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/february/asia-volunteer-projects-sri-lanka','/travel/sri-lanka/volunteer-in-sri-lanka',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/belize/tours-in-belize','/travel/belize',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/vanuatu/tours-in-vanuatu','/travel/vanuatu',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/vanuatu/volunteer-in-vanuatu','/travel/vanuatu',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/tonga/tours-in-tonga','/travel/tonga',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/tonga/volunteer-in-tonga','/travel/tonga',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/papua-new-guinea/tours-in-papua-new-guinea','/travel/papua-new-guinea',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/papua-new-guinea/volunteer-in-papua-new-guinea','/travel/papua-new-guinea',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/bahamas/tours-in-bahamas','/travel/bahamas',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/barbados/volunteer-in-barbados','/travel/barbados',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/travel/barbados/tours-in-barbados','/travel/barbados',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/june/a-guide-to-volunteering-in-australia','/travel/australia/volunteer-in-australia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/january/australia-conservation-volunteer-projects','/travel/australia/volunteer-in-australia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/january/australia-conservation-volunteering','/travel/australia/volunteer-in-australia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/news/2011/march/travel-and-volunteer-in-australia','/travel/australia/volunteer-in-australia',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/holidays/family-volunteer-holidays','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/types-of-volunteer-holidays-abroad','/category/volunteer',0,now()::timestamp);
INSERT INTO url_map (url_from,url_to,sid,date) VALUES ('/holidays/volunteer-holidays','/category/volunteer',0,now()::timestamp);
